### ISSUE TITLE
Add to Plugin Marketplace

### ISSUE THREAD

**Issue by hanzei** [phillipahereza/mattermost-plugin-digitalocean#65]
@phillipahereza and @AGMETEOR congratulations on winning the price for the hackathon. :tada:  As plugin is very handy for admins, it would be a great addition to the Plugin Marketplace. Would you be interested on submitting your plugin to the Plugin Marketplace? You can find the process for submitting your plugin [here](https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/).

Surrey, there is some more work to do before `v1.0` get released, but even a pre-release version might be suitable for the Marketplace.

**Comment by aaronrothschild** [comment]
@hanzei Was it listed as Beta to the marketplace?

**Comment by hanzei** [comment]
Indeed, thanks for the reminder @aaronrothschild. Closing.
